services:
  enum.type.registry:
    class: Enum\Bundle\Doctrine\EnumTypeRegistry
    arguments:
      - '@enum.type.generator'
      - '@enum.type.storage'

  enum.type.generator:
    class: Enum\Bundle\Doctrine\Generator\EnumTypeGenerator

  enum.type.storage.memory:
    class: Enum\Bundle\Doctrine\TypeStorage\MemoryEnumTypeStorage

  enum.type.storage.file:
    class: Enum\Bundle\Doctrine\TypeStorage\FileEnumTypeStorage
    arguments:
      - '%kernel.cache_dir%/enum'

  enum.type.storage:
    alias: enum.type.storage.memory